spring.application.name=product-service
server.port=${SERVER_PORT:8091}
spring.threads.virtual.enabled=true
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/enterprise_store_db}
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
